name: mep_dubai_app
description: Dubai MEP Q&A app with dynamic UI and CI-ready build
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pdfs/
    - assets/data/
